# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzAdyzOd5WnT82FK24nP281GaR-cmmGv
"""

import requests

API_KEY = "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"

def simplify_legal(text):
    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    prompt = f"""
Simplify this legal document:
{text}
"""

    data = {
        "model": "openai/gpt-oss-120b:free",
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(url, headers=headers, json=data)
    result = response.json()

    # 🔥 DEBUG
    print("FULL RESPONSE:", result)

    # ✅ SAFE ACCESS
    if "choices" in result:
        return result["choices"][0]["message"]["content"]
    else:
        return f"Error: {result}"

# Test
print(simplify_legal("This Agreement shall be governed by the laws of India..."))

import gradio as gr

!pip install gradio PyPDF2 python-docx pillow pytesseract

# 🔥 Install (Colab me pehle run karo)
# !pip install gradio PyPDF2 python-docx pillow pytesseract
# !apt-get install tesseract-ocr

import requests
import gradio as gr
from PyPDF2 import PdfReader
import docx
from PIL import Image
import pytesseract

# 🔑 API KEY
API_KEY = "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"

# 📄 Text Extraction
def extract_text(file):
    if file.name.endswith(".pdf"):
        reader = PdfReader(file)
        text = ""
        for page in reader.pages:
            text += page.extract_text() or ""
        return text

    elif file.name.endswith(".docx"):
        doc = docx.Document(file)
        return "\n".join([p.text for p in doc.paragraphs])

    elif file.name.endswith((".png", ".jpg", ".jpeg")):
        img = Image.open(file)
        return pytesseract.image_to_string(img)

    else:
        return "Unsupported file type"


# 🤖 AI Function
def simplify_file(file):
    text = extract_text(file)

    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    prompt = f"""
You are an expert legal assistant.

Your job is to simplify legal documents for a normal person.

--- Summary ---
Give 3-5 simple sentences

--- Key Points ---
• Bullet points

--- Important Clauses ---
• Payment Terms
• Termination
• Liability
• Obligations

--- Risks / Warnings ---
• Mention risks

--- Simplified Version ---
Rewrite in simple English

Document:
{text}
"""

    data = {
        "model": "openai/gpt-oss-120b:free",
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3
    }

    response = requests.post(url, headers=headers, json=data)
    result = response.json()

    if "choices" in result:
        return result["choices"][0]["message"]["content"]
    else:
        return f"Error: {result}"


# 🌈 Neon CSS
css = """
body { background-color: #0f172a; }
h1 {
  color: #00ffff;
  text-align:center;
  text-shadow: 0 0 10px #00ffff, 0 0 20px #00ffff;
}
button {
  background: linear-gradient(90deg,#00ffff,#ff00ff) !important;
  color: black !important;
  font-weight: bold;
  box-shadow: 0 0 15px #00ffff;
  border: none !important;
}
button:hover {
  box-shadow: 0 0 25px #ff00ff;
  transform: scale(1.05);
}
textarea {
  background-color: #020617 !important;
  color: #00ffcc !important;
  border: 1px solid #00ffff !important;
  box-shadow: 0 0 10px #00ffff;
}
"""

# 🎨 Gradio UI (Blocks Layout)
with gr.Blocks(css=css) as demo:
    gr.Markdown("# ⚡ Yori Legal Document AI Simplifier")

    file_input = gr.File(label="📄 Upload PDF / DOCX / Image")

    btn = gr.Button("🚀 Simplify Document")

    output = gr.Textbox(
        label="⚡ Simplified Output",
        lines=30,          # 🔥 BIG OUTPUT BOX
        max_lines=50,
        show_copy_button=True
    )

    btn.click(fn=simplify_file, inputs=file_input, outputs=output)

# 🚀 Launch
demo.launch()

